package com.example.ui.utils

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

val LocalAppLanguage = compositionLocalOf { "ar" }

class AppStrings(val language: String) {
    val isEn = language == "en"

    // App & Navigation
    val appTitle = if (isEn) "Smart Vault" else "الخزنة الذكية"
    val navHome = if (isEn) "Home" else "الرئيسية"
    val navSavings = if (isEn) "Savings" else "المدخرات"
    val navTransactions = if (isEn) "Transactions" else "العمليات"
    val navCommitments = if (isEn) "Commitments" else "الالتزامات"
    val navOutings = if (isEn) "Outings" else "الخروجات"
    val navReports = if (isEn) "Reports" else "التقارير"
    val navSettings = if (isEn) "Settings" else "الإعدادات"

    // Header Screen Titles
    val titleHome = if (isEn) "Smart Vault" else "الخزنة الذكية"
    val titleSavings = if (isEn) "Savings & Gold Vault" else "المدخرات والذهب 💰"
    val titleCommitments = if (isEn) "Commitments & Lessons" else "الالتزامات والدروس"
    val titleOutings = if (isEn) "Outing Expenses & Split" else "مصاريف الخروجات واللمة"
    val titleTransactions = if (isEn) "Transactions" else "العمليات"
    val titleReports = if (isEn) "Reports & Budget" else "التقارير والميزانية"
    val titleSettings = if (isEn) "Settings & Vaults" else "الإعدادات والحسابات"

    // Savings & Gold Module
    val totalSavings = if (isEn) "Total Savings" else "إجمالي المدخرات"
    val totalCashSavings = if (isEn) "Cash Savings" else "المدخرات النقدية"
    val currentGoldValue = if (isEn) "Current Gold Value" else "قيمة الذهب الحالية"
    val totalGoldWeight = if (isEn) "Total Gold Weight" else "إجمالي وزن الذهب"
    val goldPiecesCount = if (isEn) "Gold Pieces" else "عدد قطع الذهب"
    val goldProfits = if (isEn) "Gold Profits / Return" else "عائد وأرباح الذهب"
    val updateGoldPrices = if (isEn) "Update Gold Prices" else "تعديل أسعار الذهب اليوم"
    val goldPricesToday = if (isEn) "Today's Gold Prices (per gram)" else "أسعار الذهب اليوم (سعر الجرام)"
    val tabGold = if (isEn) "Gold & Bullions" else "الذهب والسبائك"
    val tabCash = if (isEn) "Cash Savings" else "المدخرات النقدية"
    val tabAnalytics = if (isEn) "Analytics & Growth" else "التحليلات والنمو"
    val tabSoldHistory = if (isEn) "Sold Gold History" else "سجل المبيعات"
    val addGoldPiece = if (isEn) "Add Gold Piece" else "إضافة قطعة ذهب / سبيكة"
    val addCashSaving = if (isEn) "Add Cash Saving" else "إضافة مدخرات نقدية"
    val goldPieceName = if (isEn) "Piece Name / Brand" else "اسم القطعة / الماركة"
    val goldType = if (isEn) "Gold Type" else "نوع الذهب"
    val bullion = if (isEn) "Bullion / Bar" else "سبيكة"
    val jewelry = if (isEn) "Jewelry" else "مشغولات"
    val goldCoin = if (isEn) "Gold Coin" else "عملة ذهبية"
    val goldPound = if (isEn) "Gold Pound (8g)" else "جنيه ذهب (8 جرام)"
    val otherGold = if (isEn) "Other" else "أخرى"
    val karat = if (isEn) "Karat" else "العيار"
    val karat24 = if (isEn) "24 Karat (999.9)" else "عيار 24 (نقاء 99.9%)"
    val karat22 = if (isEn) "22 Karat" else "عيار 22"
    val karat21 = if (isEn) "21 Karat (Standard)" else "عيار 21 (الأكثر تداولاً)"
    val karat18 = if (isEn) "18 Karat" else "عيار 18"
    val karat14 = if (isEn) "14 Karat" else "عيار 14"
    val karat12 = if (isEn) "12 Karat" else "عيار 12"
    val weightInGrams = if (isEn) "Weight in Grams (g)" else "الوزن بالجرام"
    val purchasePrice = if (isEn) "Purchase Price (Total Paid)" else "سعر الشراء الفعلي (المبلغ المدفوع)"
    val purchaseDate = if (isEn) "Purchase Date" else "تاريخ الشراء"
    val purpose = if (isEn) "Purpose" else "الغرض من الاقتناء"
    val purposeSaving = if (isEn) "For Savings / Investment" else "للادخار والاستثمار"
    val purposeAdornment = if (isEn) "For Adornment & Use" else "للزينة والاستخدام"
    val piecePhoto = if (isEn) "Piece Photo / Invoice" else "صورة القطعة أو الفاتورة"
    val sellGold = if (isEn) "Sell Gold Piece" else "تسجيل بيع القطعة"
    val salePrice = if (isEn) "Sale Price" else "سعر البيع الفعلي"
    val saleDate = if (isEn) "Sale Date" else "تاريخ البيع"
    val saleNotes = if (isEn) "Sale Notes" else "ملاحظات البيع"
    val realizedProfit = if (isEn) "Realized Profit" else "الربح المحقق"
    val profitPercentage = if (isEn) "Profit %" else "نسبة الربح"
    val lossPercentage = if (isEn) "Loss %" else "نسبة الخسارة"
    val inVault = if (isEn) "In Vault (Active)" else "في الخزنة (غير مباعة)"
    val sold = if (isEn) "Sold" else "تم البيع"
    val pieceDetails = if (isEn) "Gold Piece Details" else "تفاصيل قطعة الذهب"
    val currentGramPrice = if (isEn) "Current Gram Price" else "سعر الجرام الحالي"
    val noGoldYet = if (isEn) "No gold assets recorded yet" else "لا توجد قطع ذهب مسجلة بعد"
    val noCashSavingsYet = if (isEn) "No cash savings recorded yet" else "لا توجد مدخرات نقدية مسجلة بعد"
    val noSoldGoldYet = if (isEn) "No sold gold history recorded" else "لا توجد مبيعات ذهب مسجلة"
    val assetAllocation = if (isEn) "Asset Allocation (Gold vs Cash)" else "توزيع الأصول (ذهب مقابل كاش)"
    val savingsAdvise = if (isEn) "Savings & Wealth Insights" else "نصائح الخزنة لتنمية المدخرات"

    // Dashboard
    val welcomeUser = if (isEn) "Welcome," else "مرحباً بك،"
    val currentBalance = if (isEn) "Current Vault Balance" else "الرصيد الحالي في الخزنة"
    val monthlyIncome = if (isEn) "Monthly Income" else "دخل الشهر"
    val monthlyExpenses = if (isEn) "Monthly Expenses" else "مصروفات الشهر"
    val smartAnalytics = if (isEn) "Smart Analytics" else "التحليل الذكي"
    val totalAvailableBalance = if (isEn) "Total Available Balance" else "إجمالي الرصيد المتاح"
    val thisMonthIncome = if (isEn) "This Month's Income" else "دخل هذا الشهر"
    val thisMonthExpense = if (isEn) "This Month's Expense" else "مصروفات هذا الشهر"
    val addIncome = if (isEn) "Add Income" else "إضافة دخل"
    val addExpense = if (isEn) "Add Expense" else "إضافة مصروف"
    val financialVaults = if (isEn) "Financial Vaults & Accounts" else "الخزانات والحسابات المالية"
    val recentTransactions = if (isEn) "Recent Transactions" else "العمليات الأخيرة"
    val viewAll = if (isEn) "View All" else "عرض الكل"
    val noTransactionsYet = if (isEn) "No transactions recorded yet" else "لا توجد عمليات مسجلة حالياً"
    val monthlyCategoryBudget = if (isEn) "Monthly Category Budgets" else "الميزانية الشهرية للتصنيفات"
    val addBudgetLimit = if (isEn) "Add New Limit" else "إضافة حد جديد"
    val setBudget = if (isEn) "Set Budget" else "تحديد ميزانية"
    val noBudgetSet = if (isEn) "No budget limits set yet." else "لم يتم تحديد حدود ميزانية بعد."
    val upcomingCommitments = if (isEn) "Upcoming Commitments" else "الالتزامات القادمة"
    val childLessons = if (isEn) "Children Lessons" else "دروس الأطفال"
    val paid = if (isEn) "Paid" else "تم الدفع"
    val unpaid = if (isEn) "Unpaid" else "غير مدفوع"
    val intelligentAdvisor = if (isEn) "Smart Financial Advisor" else "المستشار المالي الذكي"
    val achievementsAndBadges = if (isEn) "Achievements & Badges" else "الإنجازات والشارات"

    // Transactions / Expenses Screen
    val filterAll = if (isEn) "All" else "الكل"
    val filterExpenses = if (isEn) "Expenses" else "المصروفات"
    val filterIncome = if (isEn) "Income" else "الدخل"
    val searchPlaceholder = if (isEn) "Search transactions..." else "بحث في العمليات..."
    val noMatchingTransactions = if (isEn) "No transactions match your search" else "لا توجد عمليات تطابق البحث"
    val transactionDetails = if (isEn) "Transaction Details" else "تفاصيل العملية"
    val deleteTransaction = if (isEn) "Delete Transaction" else "حذف العملية"
    val amount = if (isEn) "Amount" else "المبلغ"
    val date = if (isEn) "Date" else "التاريخ"
    val category = if (isEn) "Category" else "التصنيف"
    val vault = if (isEn) "Vault / Account" else "الخزنة / الحساب"
    val notes = if (isEn) "Notes" else "ملاحظات"

    // Commitments & Lessons Screen
    val name = if (isEn) "Name" else "الاسم"
    val dueDay = if (isEn) "Due Day" else "يوم الاستحقاق"
    val repeatMonthly = if (isEn) "Repeats Monthly" else "يتكرر شهرياً"
    val commitmentExample = if (isEn) "e.g. Electricity Bill" else "مثال: فاتورة الكهرباء"
    val commitmentsTab = if (isEn) "Monthly Commitments" else "الالتزامات الشهرية"
    val lessonsTab = if (isEn) "Children Lessons" else "دروس الأطفال"
    val monthlyCommitments = if (isEn) "Monthly Commitments" else "الالتزامات الشهرية"
    val addCommitment = if (isEn) "Add Commitment" else "إضافة التزام"
    val addLesson = if (isEn) "Add Lesson" else "إضافة درس"
    val teacherName = if (isEn) "Teacher / Subject" else "اسم المدرس / المادة"
    val childName = if (isEn) "Child Name" else "اسم الطفل"
    val dueDate = if (isEn) "Due Date" else "تاريخ الاستحقاق"
    val payFromVault = if (isEn) "Pay from Vault" else "تم الدفع والخصم من الخزنة"
    val noCommitments = if (isEn) "No commitments recorded" else "لا توجد التزامات مسجلة"
    val noLessons = if (isEn) "No lessons recorded" else "لا توجد دروس مسجلة"

    // Reports & Analytics Screen
    val currentMonthSummary = if (isEn) "Current Month Summary" else "ملخص الشهر الحالي"
    val remainingBalance = if (isEn) "Remaining Balance" else "المتبقي من الدخل"
    val avgDailySpend = if (isEn) "Avg Daily Spend" else "متوسط الإنفاق اليومي"
    val safeDailyLimit = if (isEn) "Safe Daily Limit" else "الحد اليومي الآمن"
    val expenseDistribution = if (isEn) "Expense Distribution by Category" else "توزيع المصروفات حسب التصنيف"
    val exportPdf = if (isEn) "Export PDF Report" else "تصدير تقرير PDF"
    val exportExcel = if (isEn) "Export Excel / CSV" else "تصدير Excel / CSV"
    val topExpenseCategory = if (isEn) "Top Expense Category" else "أعلى تصنيف إنفاقاً"
    val incomeVsExpense = if (isEn) "Income vs Expenses Comparison" else "مقارنة الدخل بالمصروفات"

    // Settings Screen
    val appPreferences = if (isEn) "App Preferences & Settings" else "تفضيلات وإعدادات التطبيق"
    val appLanguage = if (isEn) "App Language" else "لغة التطبيق"
    val arabic = if (isEn) "العربية (Arabic)" else "العربية (Arabic)"
    val english = if (isEn) "English (الإنجليزية)" else "English (الإنجليزية)"
    val appCurrency = if (isEn) "App Currency" else "عملة التطبيق"
    val darkMode = if (isEn) "Dark Mode" else "الوضع الداكن (Dark Mode)"
    val fingerprintPin = if (isEn) "Fingerprint / PIN Lock" else "قفل الخزنة ببصمة الإصبع / PIN"
    val twoFactorAuth = if (isEn) "Two-Factor Auth (2FA)" else "التحقق بخطوتين (2FA)"
    val enabled2FA = if (isEn) "Enabled - Code required on login" else "مُفعل - كود أمان عند الدخول"
    val disabled2FA = if (isEn) "Disabled" else "غير مُفعل"
    val dailyReminder = if (isEn) "Daily Expense Reminder" else "تذكير يومي بمراجعة المصروفات"
    val reminderSub = if (isEn) "Auto notification daily at 8:00 PM" else "إشعار تلقائي يومياً الساعة 8:00 مساءً"
    val backupRestore = if (isEn) "Backup & Restore Data" else "النسخ الاحتياطي واستعادة البيانات"
    val driveBackup = if (isEn) "Google Drive Backup" else "النسخ الاحتياطي على Google Drive"
    val restoreBackup = if (isEn) "Restore Backup" else "استعادة النسخة الاحتياطية"
    val editProfile = if (isEn) "Edit Profile" else "تعديل بيانات الحساب"
    val logout = if (isEn) "Logout" else "تسجيل الخروج"
    val addAccountVault = if (isEn) "Add Account / Vault" else "إضافة حساب / خزنة"

    val attachReceipt = if (isEn) "Attach Receipt Image" else "إرفاق صورة الفاتورة"
    val receiptImage = if (isEn) "Receipt Image" else "صورة الفاتورة"
    val optional = if (isEn) "Optional" else "اختياري"

    // Common Buttons & Actions
    val save = if (isEn) "Save" else "حفظ"
    val cancel = if (isEn) "Cancel" else "إلغاء"
    val delete = if (isEn) "Delete" else "حذف"
    val edit = if (isEn) "Edit" else "تعديل"
    val confirm = if (isEn) "Confirm" else "تأكيد"
    val close = if (isEn) "Close" else "إغلاق"

    // Helper to translate default categories if needed
    fun translateCategory(cat: String): String {
        if (!isEn) return cat
        return when (cat) {
            "خضروات" -> "Vegetables"
            "فاكهة" -> "Fruits"
            "طلبات منزل" -> "Groceries"
            "سوبر ماركت" -> "Supermarket"
            "مطاعم" -> "Restaurants"
            "مواصلات" -> "Transport"
            "بنزين" -> "Fuel"
            "ملابس" -> "Clothing"
            "صيدلية" -> "Pharmacy"
            "أدوية" -> "Medicines"
            "تعليم" -> "Education"
            "دروس أطفال" -> "Children Lessons"
            "إيجار المنزل" -> "House Rent"
            "إيجار" -> "Rent"
            "فاتورة الكهرباء" -> "Electricity Bill"
            "كهرباء" -> "Electricity"
            "فاتورة المياه" -> "Water Bill"
            "فاتورة الغاز" -> "Gas Bill"
            "فاتورة الإنترنت" -> "Internet Bill"
            "فاتورة الهاتف" -> "Phone Bill"
            "ترفيه" -> "Entertainment"
            "هدايا" -> "Gifts"
            "صيانة" -> "Maintenance"
            "إصلاحات" -> "Repairs"
            "قسط سيارة" -> "Car Installment"
            "أخرى" -> "Other"
            "الراتب" -> "Salary"
            "مكافأة" -> "Bonus"
            "أرباح" -> "Profits"
            "تحويل مالي" -> "Transfer"
            "الالتزامات" -> "Commitments"
            "الخزنة الرئيسية" -> "Main Vault"
            else -> cat
        }
    }

    // GoldAPI.io Live Updates
    val liveGoldPriceUpdate = if (isEn) "Live Gold Prices (GoldAPI.io)" else "تحديث أسعار الذهب لحظياً (GoldAPI.io)"
    val fetchLiveGoldPrices = if (isEn) "Live Update" else "تحديث لحظي"
    val goldApiKeyLabel = if (isEn) "GoldAPI.io Access Token" else "مفتاح الربط (Access Token)"
    val goldApiKeyHint = if (isEn) "Enter your token from goldapi.io" else "أدخل مفتاحك من موقع goldapi.io"
    val goldApiKeyExplanation = if (isEn) "Get your free API key from https://www.goldapi.io/ to enable instant real-time gold market rates." else "يمكنك الحصول على مفتاح مجاني من موقع https://www.goldapi.io/ لتحديث أسعار الذهب لحظياً في أي وقت."
    val updatingPrices = if (isEn) "Fetching live rates..." else "جاري جلب الأسعار اللحظية..."
    val pricesUpdatedSuccess = if (isEn) "Gold prices updated successfully from GoldAPI.io!" else "تم تحديث أسعار الذهب لحظياً بنجاح من GoldAPI.io!"
    val lastUpdated = if (isEn) "Last updated: " else "آخر تحديث: "
}

val LocalStrings = compositionLocalOf { AppStrings("ar") }
